package com.example.IIS.dto;

public enum WorkshopCategoryDto {
    ANXIETY_MANAGEMENT,
    STRESS_REDUCING_TECHNIQUES,
    MINDFULNESS_BASED_STRESS_REDUCTION,
    EMOTIONAL_INTELLIGENCE,
    SELF_COMPASSION,
    COGNITIVE_BEHAVIORAL_THERAPY,
    POSITIVE_PSYCHOLOGY,
    ASSERTIVENESS_TRAINING,
    ASSERTIVE_COMMUNICATION,
    CONFLICT_RESOLUTION,
    ANGER_MANAGEMENT,
    MENTAL_HEALTH_AWARENESS,
    DEPRESSION_MANAGEMENT,
    SELF_ESTEEM_BUILDING,
    COUPLES_THERAPY,
    FAMILY_THERAPY,
    CHILD_PSYCHOLOGY,
    TRAUMA_RECOVERY,
    ADDICTION_RECOVERY,
    GRIEF_COUNSELING,
    LIFE_TRANSITIONS,
    MIND_BODY_CONNECTION,
    SLEEP_MANAGEMENT
}
